//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;environment&quot;: &quot;production&quot;,
        ///  &quot;template&quot;: &quot;Whirlpool (Hot Wort Receiver)&quot;,
        ///  &quot;rule&quot;: &quot;Batch_Step_Start_Empty&quot;,
        ///  &quot;asset_global_codification_id&quot;: &quot;1.12.19.143.1.2-1.934-1.0&quot;,
        ///  &quot;event_type_code&quot;: &quot;6&quot;,
        ///  &quot;event_type_name&quot;: &quot;Batch Step Start&quot;,
        ///  &quot;pts_code&quot;: &quot;&quot;,
        ///  &quot;pi_code&quot;: &quot;&quot;,
        ///  &quot;collect_time&quot;: 1727670519238,
        ///  &quot;event&quot;: &quot;TEMPLATE_DATA&quot;,
        ///  &quot;values&quot;: {
        ///    &quot;1.12.19.143.1.2-1.934-1.0.7238&quot;: 3702,
        ///    &quot;1.12.19.143.1.2-1.934-1.0.7244&quot;: 5,
        ///    &quot;1.12.19.143.1.2-1.934-1.0.7240&quot;: 1
        ///  },
        ///  &quot;values_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_event {
            get {
                return ResourceManager.GetString("template-event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;environment&quot;: &quot;production&quot;,
        ///  &quot;template&quot;: &quot;Whirlpool (Hot Wort Receiver)&quot;,
        ///  &quot;rule&quot;: &quot;Cooling Duration&quot;,
        ///  &quot;asset_global_codification_id&quot;: &quot;1.12.19.143.1.2-1.934-1.0&quot;,
        ///  &quot;event_type_code&quot;: &quot;0&quot;,
        ///  &quot;event_type_name&quot;: &quot;&quot;,
        ///  &quot;pts_code&quot;: &quot;P.BR.BH.WCO.0013&quot;,
        ///  &quot;pi_code&quot;: &quot;&quot;,
        ///  &quot;collect_time&quot;: 1727674131237,
        ///  &quot;event&quot;: &quot;TEMPLATE_DATA&quot;,
        ///  &quot;values&quot;: {
        ///    &quot;1.12.19.143.1.2-1.934-1.0.7238&quot;: 3702,
        ///    &quot;1.12.19.143.1.2-1.934-1.0.7093&quot;: 58.54999923706055
        ///  },
        ///  &quot;values_details&quot;: {},
        ///  &quot;quality_rate&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_parameter {
            get {
                return ResourceManager.GetString("template-parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;environment&quot;: &quot;production&quot;,
        ///  &quot;template&quot;: &quot;Filler&quot;,
        ///  &quot;rule&quot;: &quot;Performance Data Recurrent&quot;,
        ///  &quot;asset_global_codification_id&quot;: &quot;1.12.12.191.2.31-1.32-1.0&quot;,
        ///  &quot;event_type_code&quot;: &quot;0&quot;,
        ///  &quot;event_type_name&quot;: &quot;&quot;,
        ///  &quot;pts_code&quot;: &quot;&quot;,
        ///  &quot;pi_code&quot;: &quot;&quot;,
        ///  &quot;collect_time&quot;: 1727727935144,
        ///  &quot;event&quot;: &quot;TEMPLATE_DATA&quot;,
        ///  &quot;values&quot;: {
        ///    &quot;1.12.12.191.2.31-1.32-1.0.7247&quot;: 128,
        ///    &quot;1.12.12.191.2.31-1.32-1.0.7291&quot;: 128138795,
        ///    &quot;1.12.12.191.2.31-1.32-1.0.7290&quot;: 0,
        ///    &quot;1.12.12.191.2.31-1.32-1.0.7292&quot;: null        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_performance {
            get {
                return ResourceManager.GetString("template-performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;environment&quot;: &quot;production&quot;,
        ///  &quot;template&quot;: &quot;Brew Kettle (Wort Kettle)&quot;,
        ///  &quot;rule&quot;: &quot;Transfer to WP101&quot;,
        ///  &quot;asset_global_codification_id&quot;: &quot;1.12.19.143.1.2-1.859-1.0&quot;,
        ///  &quot;event_type_code&quot;: &quot;25&quot;,
        ///  &quot;event_type_name&quot;: &quot;Transfer Out End&quot;,
        ///  &quot;pts_code&quot;: &quot;&quot;,
        ///  &quot;pi_code&quot;: &quot;&quot;,
        ///  &quot;collect_time&quot;: 1727669438121,
        ///  &quot;event&quot;: &quot;TEMPLATE_DATA&quot;,
        ///  &quot;values&quot;: {
        ///    &quot;1.12.19.143.1.2-1.859-1.0.7093&quot;: 345,
        ///    &quot;1.12.19.143.1.2-1.859-1.0.7300&quot;: &quot;2&quot;,
        ///    &quot;1.12.19.143.1.2-1.859-1.0.7238&quot;: 3702,
        ///    &quot;1.12.19.143.1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_transfer {
            get {
                return ResourceManager.GetString("template-transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap worker {
            get {
                object obj = ResourceManager.GetObject("worker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
